test: &test
  aleph_rest_url: http://aleph2.library.nd.edu:1891/
  aleph_xservices_url: http://aleph2.library.nd.edu:8991/X
  aleph_xservices_username: 'APIANNEX'
  aleph_xservices_password: 'AnnexAPI'
  aleph_xservices_borrower_path: '?op=<<op>>&library=ndu50&bor_id=<<bor_id>>&loans=Y'
  illiad_transactions_url: https://nd.illiad.oclc.org/ILLiadWebPlatform/Transaction/UserRequests/
  illiad_api_key: '817e6405-9be9-4794-add6-70015edd3d86'
  illiad_checked_out_filter_path: "<<netid>>?$filter=(TransactionStatus eq 'Checked Out to Customer')"
  illiad_available_web_filter_path: "<<netid>>?$filter=(TransactionStatus eq 'Delivered to Web')"
  illiad_pending_filter_path: "<<netid>>?$filter=(TransactionStatus ne 'Request Finished') and not startswith(TransactionStatus, 'Cancel') and not (TransactionStatus eq 'Delivered to Web') and not (TransactionStatus eq 'Checked Out to Customer')"


production: &production
  aleph_rest_url: http://alephprod.library.nd.edu:1891/
  aleph_xservices_url: http://alephprod.library.nd.edu:8991/X
  aleph_xservices_username: 'APIANNEX'
  aleph_xservices_password: 'AnnexAPI'
  aleph_xservices_item_path: '?op=read-item&library=ndu50&barcode=<<barcode>>'

development:
  <<: *test

pre_production:
  <<: *test
