# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

#     services:
#       mysql:
#         image: mariadb:10.2.34
#         ports:
#           - 3306:3306
#         env:
#           MYSQL_ALLOW_EMPTY_PASSWORD: yes
#         options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
    # uses: ruby/setup-ruby@v1
      uses: ruby/setup-ruby@ec106b438a1ff6ff109590de34ddc62c540232e0
      with:
        ruby-version: 2.4
    - name: Start mysql
      run: sudo systemctl start mysql.service
    - name: Install bundler
      run: gem install bundler:1.17.3
    - name: Install dependencies
      run: bundle install
    - name: Pre-test steps
      env:
        MYSQL_PASSWORD: root
      run: |
        cp config/secrets.example.yml config/secrets.yml
        mysql -uroot -p$MYSQL_PASSWORD -c 'create database factotum_test'
        RAILS_ENV=test bundle exec rake --trace db:migrate test
    - name: Run tests
      run: bundle exec rspec spec
